{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2021-22877",
      "ASSIGNER": "support@hackerone.com"
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-862"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://github.com/nextcloud/server/issues/24600",
          "name": "https://github.com/nextcloud/server/issues/24600",
          "refsource": "MISC",
          "tags": [
            "Exploit",
            "Issue Tracking",
            "Patch",
            "Third Party Advisory"
          ]
        },
        {
          "url": "https://github.com/nextcloud/server/pull/25224",
          "name": "https://github.com/nextcloud/server/pull/25224",
          "refsource": "MISC",
          "tags": [
            "Patch",
            "Third Party Advisory"
          ]
        },
        {
          "url": "https://nextcloud.com/security/advisory/?id=NC-SA-2021-004",
          "name": "https://nextcloud.com/security/advisory/?id=NC-SA-2021-004",
          "refsource": "MISC",
          "tags": [
            "Broken Link",
            "Vendor Advisory"
          ]
        },
        {
          "url": "https://hackerone.com/reports/1061591",
          "name": "https://hackerone.com/reports/1061591",
          "refsource": "MISC",
          "tags": [
            "Issue Tracking",
            "Third Party Advisory"
          ]
        },
        {
          "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/L6BO6P6MP2MOWA6PZRXX32PLWPXN5O4S/",
          "name": "FEDORA-2021-eac0e52f88",
          "refsource": "",
          "tags": []
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A missing user check in Nextcloud prior to 20.0.6 inadvertently populates a user's own credentials for other users external storage configuration when not already configured yet."
        }
      ]
    }
  },
  "configurations": {
    "nodes": [
      {
        "operator": "OR",
        "cpe_match": [
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:a:nextcloud:nextcloud_server:*:*:*:*:*:*:*:*"
          }
        ]
      },
      {
        "operator": "OR",
        "cpe_match": [
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:o:fedoraproject:fedora:34:*:*:*:*:*:*:*"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "vectorString": "AV:N/AC:L/Au:S/C:P/I:P/A:N",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "SINGLE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "availabilityImpact": "NONE",
        "baseScore": 5.5
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 8,
      "impactScore": 4.9,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2021-03-03T18:15Z",
  "lastModifiedDate": "2023-11-07T03:30Z"
}